language: php
php:
  - hhvm
  - 7.0
  - 5.5
  - 5.4
  - 5.3

matrix:
    allow_failures:
        - php: 7.0

script: phpunit --c tests/phpunit.xml

notifications:
  recipients:
    - david.gorges@leaphub.de
  on_success: change
  on_failure: always