language: php
php:
  - hhvm
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.5
  - 5.4

matrix:
    allow_failures:
        - php: 7.1
        - php: 7.2
        - php: 5.5
        - php: 5.4

before_script:
    - composer install --prefer-source

script:
    - phpunit --configuration tests/phpunit.xml

notifications:
  recipients:
    - david.gorges@leaphub.de
  on_success: change
  on_failure: always